config/routes.rb
Rails.application.routes.draw do
  resources :closing_groups
  resources :earnings
  resources :delivery_slips
  resources :orders
  resources :order_details, only: [:show]
  resources :estimates do
    member do
      get :report
    end
  end
  resources :sales_reports
  resources :prospects
  resources :products
  resources :customers do
    collection do
      get :import_form
      post :import
    end
  end
  resources :company_informations, only: [:edit, :update]
  resources :user_profiles
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :user_registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations'
  end

  root to: 'static_pages#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/estimate.rb
require 'bigdecimal'

class Estimate < ApplicationRecord
  belongs_to :company_information
  belongs_to :prospect, optional: true
  belongs_to :customer
  belongs_to :user_profile
  has_many :estimate_details, dependent: :destroy
  accepts_nested_attributes_for :estimate_details, allow_destroy: true, limit: 10
  before_validation :save_customer_name
  before_validation :set_estimate_no
  before_validation :set_company_information, on: :create
  before_destroy :can_destroy?
  after_initialize :set_default_tax_rate

  MIN_DETAILS_SIZE = 1
  MAX_DETAILS_SIZE = 10
  DEFAULT_TAX_RATE = 8

  validates :title, presence: true, length: { maximum: 70 }
  validates :customer, presence: true
  validates :customer_name, presence: true, length: { maximum: 50 }
  validates :estimate_no, presence: true, length: { maximum: 14 }, uniqueness: { scope: [:company_information_id, :estimate_no] }
  validates :issue_date, presence: true
  validates :due_date, presence: true, unless: :due_date_pending_flag
  validates :due_date_pending_flag, inclusion: { in: [true, false] }
  validates :payment_term, presence: true, length: { maximum: 50 }
  validates :effective_date, presence: true
  validates :tax_rate, presence: true, numericality: { greater_than_or_equal_to: 0, less_than: 100 }
  validates :remarks, length: { maximum: 1000 }
  validate :details_count_validate
  validates :submitted_flag, inclusion: { in: [true, false] }
  validates :ordered_flag, inclusion: { in: [true, false] }

  scope :search, -> (word) {
    joins(:customer).joins(:user_profile).where("title LIKE :word OR customers.name LIKE :word OR user_profiles.name LIKE :word", word: "\%#{word}\%")
  }

  def total_price
    estimate_details.sum(&:price)
  end

  private

    def details_count_validate
      errors.add(:estimate_details, I18n.t('activerecord.errors.messages.too_many_details')) if estimate_details.size > MAX_DETAILS_SIZE
      errors.add(:estimate_details, I18n.t('activerecord.errors.messages.too_few_details')) if estimate_details.size < MIN_DETAILS_SIZE
    end

    def save_customer_name
      return if customer.blank?
      self[:customer_name] = customer.name
    end

    def can_destroy?
      if submitted_flag
        errors.add(:base, '.can_not_destroy_submitted_estimate')
        throw :abort
      end
      if ordered_flag
        errors.add(:base, '.can_not_destroy_ordered_estimate')
        throw :abort
      end
    end

    def set_default_tax_rate
      return if persisted?
      self.tax_rate = DEFAULT_TAX_RATE
    end

    def set_estimate_no
      return if persisted?
      company_information.increment(:last_estimate_no)
      eno = sprintf("%014d", company_information.last_estimate_no)
      self.estimate_no = eno
    end

    def set_company_information
      self.company_name = company_information.name
      self.postal_code = company_information.postal_code
      self.address1 = company_information.address1
      self.address2 = company_information.address2
      self.email = company_information.email
      self.tel = company_information.tel
      self.fax = company_information.fax
    end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_estimate, only: [:show, :report, :edit, :update, :destroy]
  before_action :set_users
  before_action :set_customers
  before_action :set_prospects
  before_action :set_products

  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = current_user_company.estimates.search(params[:query]).order(created_at: :desc).paginate(page: params[:page], per_page: 20)
    @query = params[:query]
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
  end

  def report
    render 'report', layout: false
  end

  # GET /estimates/new
  def new
    @estimate = current_user_company.estimates.build
    @estimate.estimate_details.build
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = current_user_company.estimates.build(estimate_params)

    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: t('.estimate_was_successfully_created') }
        format.json { render :show, status: :created, location: @estimate }
      else
        format.html { render :new }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to @estimate, notice: t('.estimate_was_successfully_updated') }
        format.json { render :show, status: :ok, location: @estimate }
      else
        format.html { render :edit }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    respond_to do |format|
      if @estimate.destroy
        format.html { redirect_to estimates_url, notice: t('.estimate_was_successfully_destroyed') }
      else
        format.html { redirect_to estimates_url, notice: t('.estimate_was_fail_destroyed') }
      end
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find_by!(id: params[:id], company_information: current_user_company)
    end

    def set_users
      @users = current_user_company.user_profiles
    end

    def set_customers
      @customers = current_user_company.customers
    end

    def set_prospects
      @prospects = current_user_company.prospects
    end

    def set_products
      @products = current_user_company.products
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:company_information_id, :prospect_id, :title, :customer_id, :customer_name, :issue_date, :due_date, :due_date_pending_flag, :payment_term, :effective_date, :tax_rate, :remarks, :user_profile_id, :submitted_flag, :ordered_flag, estimate_details_attributes: [:id, :_destroy, :display_order, :product_id, :product_name, :quantity, :unit_price])
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
  def display_due_date(estimate)
    return estimate.due_date.to_s(:date) unless estimate.due_date_pending_flag
    t('estimates.helper.due_date_pending')
  end

  def submitted_estimate_message(estimate)
    if estimate.submitted_flag
      t('estimates.helper.submitted')
    else
      t('estimates.helper.unsubmitted')
    end
  end

  def ordered_estimate_message(estimate)
    if estimate.ordered_flag
      t('estimates.helper.ordered')
    else
      t('estimates.helper.non_ordered')
    end
  end
end

app/views/estimates/_estimate_detail_fields.html.erb
<tr class="nested-fields">
  <td class="d-none"><%= f.text_field :display_order, class: 'form-control form-control-sm estimate-detail-display-order' %></td>
  <td><%= f.select :product_id, @products.map{|p| [p.name, p.id]}, {include_blank: true}, class: 'form-control searchable form-control-sm product-select' %></td>
  <td><%= f.text_field :product_name, class: 'form-control form-control-sm product-name' %></td>
  <td><%= f.text_field :quantity, class: 'form-control form-control-sm estimate-detail-quantity numeric-text', value: number_to_currency(f.object.quantity.to_f, delimiter: '', unit: '') %></td>
  <td><%= f.text_field :unit_price, class: 'form-control form-control-sm estimate-detail-unit-price default-price numeric-text', value: number_to_currency(f.object.unit_price.to_f, delimiter: '', unit: '') %></td>
  <td><%= f.text_field :price, disabled: true, class: 'form-control form-control-sm estimate-detail-price numeric-text' %></td>
  <td><%= link_to_remove_association t('.remove_detail'), f, class: 'btn btn-danger btn-sm remove-detail-button' %></td>
</tr>

app/views/estimates/_form.html.erb
<%= form_with(model: estimate, local: true, class: 'form-horizontal', id: 'estimate-submit-form') do |form| %>
  <%= render 'shared/error_messages', object: estimate %>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :prospect_id, class: 'control-label' %>
          </div>
          <div class="col-sm-9">
            <%= form.select :prospect_id, @prospects.map{|p| [p.title, p.id]}, { include_blank: true }, class: 'form-control form-control-sm searchable', id: :estimate_prospect_id %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :title, class: 'control-label' %>
          </div>
          <div class="col-sm-9">
            <%= form.text_field :title, id: :estimate_title, class: 'form-control form-control-sm' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :customer_id, class: 'control-label' %>
          </div>
          <div class="col-sm-9">
            <%= form.select :customer_id, @customers.map{|c| [c.name, c.id]}, {include_blank: true}, class: 'form-control form-control-sm searchable', id: :estimate_customer_id %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :due_date, class: 'control-label' %>
          </div>
          <div class="col-sm-4">
            <%= form.date_field :due_date, id: :estimate_due_date, class: 'form-control form-control-sm' %>
          </div>
          <div class="col-sm-3">
            <%= form.check_box :due_date_pending_flag, id: :estimate_due_date_pending_flag, class: 'form-control form-control-sm button-checkbox' %>
            <%= form.label :due_date_pending_flag, class: 'control-label button-label btn btn-outline-success' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :effective_date, class: 'control-label' %>
          </div>
          <div class="col-sm-4">
            <%= form.date_field :effective_date, id: :estimate_effective_date, class: 'form-control form-control-sm' %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= label_tag t('activerecord.attributes.estimate.total_amount'), nil, class: 'control-label' %>
          </div>
          <div class="col-sm-3">
            <span class="font-weight-bold"><span id="total-amount"></span>円</span>
          </div>
          <%= form.label :tax_rate, class: 'control-label col-sm-3' %>
          <div class="col-sm-2">
            <%= form.text_field :tax_rate, class: 'form-control form-control-sm', id: 'tax-rate' %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-5">
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :estimate_no, class: 'control-label' %>
          </div>
          <div class="col-sm-5">
            <%= form.text_field :estimate_no, id: :estimate_estimate_no, class: 'form-control form-control-sm', disabled: true %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :issue_date, class: 'control-label' %>
          </div>
          <div class="col-sm-5">
            <%= form.date_field :issue_date, id: :estimate_issue_date, class: 'form-control form-control-sm' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-3">
            <%= form.label :payment_term, class: 'control-label' %>
          </div>
          <div class="col-sm-9">
            <%= form.text_field :payment_term, id: :estimate_payment_term, class: 'form-control form-control-sm' %>
          </div>
        </div>
        <div class="form-group">
          <div class="field row">
            <div class="col-sm-3">
              <%= form.label :user_profile_id, class: 'control-label' %>
            </div>
            <div class="col-sm-9">
              <%= form.select :user_profile_id, @users.map{|u| [u.name, u.id]}, {}, class: 'form-control form-control-sm searchable' %>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field row">
          <div class="col-sm-7">
            <span>
              <%= form.check_box :submitted_flag, id: :estimate_submitted_flag, class: 'form-control form-control-sm button-checkbox' %>
              <%= form.label :submitted_flag, class: 'control-label button-label btn btn-outline-success' %>
            </span>
            <span>
              <%= form.check_box :ordered_flag, id: :estimate_ordered_flag, class: 'form-control form-control-sm button-checkbox' %>
              <%= form.label :ordered_flag, class: 'control-label button-label btn btn-outline-success' %>
            </span>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="field row">
        </div>
      </div>
    </div>
  </div>
  
  <div class="details col-sm-12">
    <table class="col-sm-12">
      <thead>
        <tr>
          <th class="d-none"><%= t('activerecord.attributes.estimate_detail.display_order') %></th>
          <th style="width: 320px"><%= t('activerecord.attributes.estimate_detail.product_id') %></th>
          <th style="width: 320px"><%= t('activerecord.attributes.estimate_detail.product_name') %></th>
          <th style="width: 70px"><%= t('activerecord.attributes.estimate_detail.quantity') %></th>
          <th style="width: 150px"><%= t('activerecord.attributes.estimate_detail.unit_price') %></th>
          <th style="width: 150px"><%= t('activerecord.attributes.estimate_detail.price') %></th>
          <th><%= link_to_add_association t('.add_detail'), form, :estimate_details,
          data: {
            association_insertion_node: '#estimate_details',
            association_insertion_method: 'append'
          },
          class: 'btn btn-info btn-sm',
          id: 'add-detail-btn'
      %></th>
       </tr>
      </thead>
      <tbody id="estimate_details">
        <%= form.fields_for :estimate_details do |detail| %>
          <%= render 'estimate_detail_fields', f: detail %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :remarks, class: 'control-label col-sm-4' %>
      <div class="col-sm-11">
        <%= form.text_area :remarks, id: :estimate_remarks, rows: 5, class: 'form-control form-control-sm' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="actions">
      <%= form.submit class: 'btn btn-primary col-sm-1' %>
    </div>
  </div>

<% end %>

app/views/estimates/edit.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<%= render 'form', estimate: @estimate %>

app/views/estimates/index.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<div class="row">
  <%= form_tag estimates_path, method: :get, class: 'col-sm-6' do %>
    <div class="input-group input-group-sm">
      <%= text_field_tag :query, @query, class: 'form-control input-sm', placeholder: t('.search_placeholder') %>
      <span class="input-group-btn">
        <%= button_tag class: 'btn btn-default btn-sm' do %>
          <%= content_tag :span, t('.search') %>
        <% end %>
      </span>
    </div>
  <% end %>
  <div class="pull-right col-sm-2">
    <%= link_to t('.new_estimate'), new_estimate_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

<div class="row mt-3"></div>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th></th>
      <th><%= t('activerecord.attributes.estimate.prospect_id') %></th>
      <th><%= t('activerecord.attributes.estimate.title') %></th>
      <th><%= t('activerecord.attributes.estimate.customer_name') %></th>
      <th><%= t('activerecord.attributes.estimate.estimate_no') %></th>
      <th><%= t('activerecord.attributes.estimate.issue_date') %></th>
      <th><%= t('activerecord.attributes.estimate.ordered_flag') %></th>
      <th><%= t('activerecord.attributes.estimate.user_profile_id') %></th>
    </tr>
  </thead>

  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= link_to t('.show'), estimate, class: 'btn btn-info btn-sm' %></td>
        <td><%= estimate.prospect.try(:title) %></td>
        <td><%= estimate.title %></td>
        <td><%= estimate.customer_name %></td>
        <td><%= estimate.estimate_no %></td>
        <td><%= estimate.issue_date %></td>
        <td><%= ordered_estimate_message(estimate) %></td>
        <td><%= estimate.user_profile.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @estimates, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/estimates/new.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<%= render 'form', estimate: @estimate %>

app/views/estimates/report.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "estimate_report", media: 'all' %>
  </head>
  <body>
    <h1><span id="estimate-title"><%= t('.title') %></span></h1>

    <div id="header-container">
      <div id="left-block">
        <div id="left-block-strong-area">
          <div id="customer-name-block"><span id="customer-name"><%= @estimate.customer_name %></span><%= t('.for_the_attention') %></div>
          <div id="title"><%= t('.estimate_title') %>:<%= @estimate.title %></div>
          <div id="greeting-message"><%= t('.greeting_message') %></div>
        </div>
  
        <div class="left-block-elements"><%= t('.due_date') %>:<%= @estimate.due_date.to_s %></div>
        <div class="left-block-elements"><%= t('.payment_term') %>:<%= @estimate.payment_term %></div>
        <div class="left-block-elements"><%= t('.effective_date') %>:<%= @estimate.effective_date.to_s %></div>
        <div id="total-price"><%= t('.total_price') %>:<span id="total-price-num" class="left-block-elements"><%= @estimate.total_price.to_s(:delimited) %><%= t('.yen') %></span></div>
      </div>
  
      <div id="right-block">
        <div class="right-block-elements"><%= t('.estimate_no') %>: <%= @estimate.estimate_no %></div>
        <div class="right-block-elements"><%= t('.issue_date') %>: <%= @estimate.issue_date.to_s %></div>
    
        <div class="right-block-elements"><%= @estimate.company_name %></div>
        <div class="right-block-elements"><%= t('.postal_code') %><%= @estimate.postal_code %></div>
        <div class="right-block-elements"><%= @estimate.address1 %></div>
        <div class="right-block-elements"><%= @estimate.address2 %></div>
        <div class="right-block-elements"><%= t('.email') %>:<%= @estimate.email %></div>
        <div class="right-block-elements"><%= t('.tel') %>:<%= @estimate.tel %></div>
        <div class="right-block-elements"><%= t('.fax') %>:<%= @estimate.fax %></div>
      </div>
    </div>

    <div id="details-area">
      <table id="details">
        <thead>
          <tr>
            <th class="detail-no"><%= t('.display_order') %></th>
            <th class="detail-item-name"><%= t('.product_name') %></th>
            <th class="detail-quantity"><%= t('.quantity') %></th>
            <th class="detail-unit-price"><%= t('.unit_price') %></th>
            <th class="detail-price"><%= t('.price') %></th>
          </tr>
        </thead>
        <tbody>
          <% @estimate.estimate_details.each do |detail| %>
          <tr>
            <td class="detail-no"><%= detail.display_order %></td>
            <td class="detail-item-name"><%= detail.product_name %></td>
            <td class="detail-quantity"><%= detail.quantity %></td>
            <td class="detail-unit-price"><%= detail.unit_price.to_s(:delimited) %></td>
            <td class="detail-price"><%= (detail.quantity * detail.unit_price).to_s(:delimited) %></td>
          </tr>
          <% end %>
          <% (10 - @estimate.estimate_details.count).times do |i| %>
          <tr>
            <td class="detail-no"></td>
            <td class="detail-item-name"></td>
            <td class="detail-quantity"></td>
            <td class="detail-unit-price"></td>
            <td class="detail-price"></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div id="remarks-area">
      <div><%= t('.remarks') %>:</div>
      <div id="remarks"><%= @estimate.remarks %></div>
    </div>
  </body>
</html>

app/views/estimates/show.html.erb
<div class="row mt-1"></div>

<div class="row">
  <div class="col-sm-2">
    <span class="badge badge-info"><%= submitted_estimate_message(@estimate) %></span>
    <span class="badge badge-success"><%= ordered_estimate_message(@estimate) %></span>
  </div>
  <div class="col-sm-3"></div>
  <div class="col-sm-2">
    <button id="estimate-print-btn" class="btn btn-primary btn-sm"><%= t('.print') %></button>
    <%= link_to t('.edit'), edit_estimate_path(@estimate), class: 'btn btn-warning btn-sm' %>
    <% unless (@estimate.submitted_flag || @estimate.ordered_flag) %>
      <%= link_to t('.destroy'), @estimate, method: :delete, data: { confirm: t('.are_you_sure') }, class: 'btn btn-danger btn-sm' %>
    <% end %>
  </div>
</div>

<div class="row mt-1"></div>

<div class="row">
  <div class="col-sm-7">
    <iframe id="estimate-frame" src="<%= report_estimate_path(@estimate) %>"></iframe>
  </div>
</div>