config/routes.rb
Rails.application.routes.draw do
  resources :closing_groups
  resources :earnings
  resources :delivery_slips
  resources :orders
  resources :order_details, only: [:show]
  resources :estimates do
    member do
      get :report
    end
  end
  resources :sales_reports
  resources :prospects
  resources :products
  resources :customers do
    collection do
      get :import_form
      post :import
    end
  end
  resources :company_informations, only: [:edit, :update]
  resources :user_profiles
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :user_registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations'
  end

  root to: 'static_pages#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/customer.rb
require 'csv'

class Customer < ApplicationRecord
  belongs_to :company_information
  has_many :sales_reports, dependent: :restrict_with_error
  has_many :prospects, dependent: :restrict_with_error
  has_many :estimates, dependent: :restrict_with_error

  validates :name, presence: true, length: { maximum: 50 }
  validates :payment_term, length: { maximum: 50 }

  scope :search, -> (word) {
    where("name LIKE :word", word: "\%#{word}\%")
  }

  def latest_prospects(limit_size)
    prospects.order(created_at: :desc).limit(limit_size)
  end

  def latest_sales_reports(limit_size)
    sales_reports.order(occur_date: :desc).limit(limit_size)
  end

  def latest_estimates(limit_size)
    estimates.order(issue_date: :desc).limit(limit_size)
  end

  def self.import(file, company)
    ret = nil
    Customer.transaction do
      CSV.foreach(file.path, encoding: 'sjis', headers: true).with_index(2) do |row, i|
        obj = new
        obj.company_information = company
        obj.name = row.to_hash[I18n.t('activerecord.attributes.customer.name')]
        obj.payment_term = row.to_hash[I18n.t('activerecord.attributes.customer.payment_term')]

        ret = [i, obj]
        obj.save!
      end
    end
  rescue ActiveRecord::RecordInvalid
    return ret
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :set_latest_prospects, only: [:show]
  before_action :set_latest_sales_reports, only: [:show]

  # GET /customers
  # GET /customers.json
  def index
    @customers = current_user_company.customers.search(params[:query]).order(:name)
    @query = params[:query]

    respond_to do |format|
      format.html do
        @customers = @customers.paginate(page: params[:page], per_page: 20)
        render :index
      end
      format.csv { send_data render_to_string, filename: 'customers.csv', type: 'text/csv; charset=shift_jis' }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = current_user_company.customers.build
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = current_user_company.customers.build(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: t('.customer_was_successfully_created') }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: t('.customer_was_successfully_updated') }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: t('.customer_was_successfully_destroyed') }
      format.json { head :no_content }
    end
  end

  def import_form
  end

  def import
    if params[:file].nil?
      flash[:danger] = t('.file_must_be_spec')
      render 'import_form'
      return
    end

    @error_line, @error_customer = Customer.import(params[:file], current_user_company)
    flash[:notice] = t('.import_success') unless @error_customer
    render 'import_form'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find_by!(id: params[:id], company_information: current_user_company)
    end

    def set_latest_prospects
      @latest_prospects = @customer.latest_prospects(5)
    end

    def set_latest_sales_reports
      @latest_sales_reports = @customer.latest_sales_reports(5)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :payment_term)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true, class: 'form-horizontal') do |form| %>
  <%= render 'shared/error_messages', object: customer %>

  <div class="form-group">
    <div class="field">
      <%= form.label :name, class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= form.text_field :name, id: :customer_name, class: 'form-control form-control-sm' %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <div class="field">
      <%= form.label :payment_term, class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= form.text_field :payment_term, id: :customer_payment_term , class: 'form-control form-control-sm' %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-1"></div>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary col-sm-1' %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<%= render 'form', customer: @customer %>

app/views/customers/import_form.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<div class="row mt-3"></div>

<p>
<%= t('.description_csv_file') %>
</p>

<%= form_tag(import_customers_path, method: 'post', multipart: true) do |f| %>
  <%= file_field_tag :file %>
  <%= submit_tag t('.import_csv'), class: 'btn btn-success btn-sm' %>
<% end %>

<% if @error_customer %>
  <%= @error_line %><%= t('.import_error_occured') %>
  <%= render 'shared/error_messages', object: @error_customer %>
<% end %>

app/views/customers/index.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<div class="row">
  <%= form_tag customers_path, method: :get, class: 'col-sm-6' do %>
    <div class="input-group input-group-sm">
      <%= text_field_tag :query, @query, class: 'form-control input-sm', placeholder: t('.search_word_placeholder') %>
      <span class="input-group-btn">
        <%= button_tag class: 'btn btn-default btn-sm' do %>
          <%= content_tag :span, t('.search') %>
        <% end %>
        <%= link_to t('.save_to_csv'), customers_path(format: :csv), class: 'btn btn-sm btn-success' %>
      </span>
    </div>
  <% end %>

  <div class="pull-right col-sm-4">
    <%= link_to t('.new_entry'), new_customer_path, class: 'btn btn-primary btn-sm' %>
    <%= link_to t('.import_from_csv'), import_form_customers_path %>
  </div>
</div>

<div class="row mt-3"></div>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th></th>
      <th><%= t('activerecord.attributes.customer.name') %></th>
      <th><%= t('activerecord.attributes.customer.payment_term') %></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to t('.open'), customer, class: 'btn btn-info btn-sm' %></td>
        <td><%= customer.name %></td>
        <td><%= customer.payment_term %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @customers, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/customers/new.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<div class="row">
  <div class="col-sm-2">
    <strong><%= t('activerecord.attributes.customer.name') %>:</strong>
  </div>
  <div class="col-sm-4">
    <%= @customer.name %>
  </div>
  <div class="col-sm-2">
    <%= link_to t('.edit'), edit_customer_path(@customer), class: 'btn btn-warning btn-sm' %>
    <%= link_to t('.destroy'), @customer, method: :delete, data: { confirm: t('.are_you_sure') }, class: 'btn btn-danger btn-sm' %>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">
    <strong><%= t('activerecord.attributes.customer.payment_term') %>:</strong>
  </div>
  <div class="col-sm-4">
    <%= @customer.payment_term %>
  </div>
</div>

<div class="row mt-3"></div>
<div class="row">
  <div class="col-sm-6">
    <h6><%= t('.latest_sales_reports') %></h6>
    <table class="table table-sm">
      <thead>
        <tr>
          <th></th>
          <th><%= t('activerecord.attributes.sales_report.occur_date') %></th>
          <th><%= t('activerecord.attributes.sales_report.description') %></th>
        </tr>
      </thead>
      <tbody>
        <% @latest_sales_reports.each do |report| %>
        <tr>
          <td><%= link_to t('.open'), report, class: 'btn btn-info btn-sm' %></td>
          <td><%= report.occur_date&.to_s(:date) %></td>
          <td><%= report.description&.truncate(50) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-6">
    <h6><%= t('.latest_prospects') %></h6>
    <table class="table table-sm">
      <thead>
        <tr>
          <th></th>
          <th><%= t('activerecord.attributes.prospect.title') %></th>
        </tr>
      </thead>
      <tbody>
        <% @latest_prospects.each do |prospect| %>
        <tr>
          <td><%= link_to t('.open'), prospect, class: 'btn btn-info btn-sm' %></td>
          <td><%= prospect.title.truncate(50) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>