config/routes.rb
Rails.application.routes.draw do
  resources :closing_groups
  resources :earnings
  resources :delivery_slips
  resources :orders
  resources :order_details, only: [:show]
  resources :estimates do
    member do
      get :report
    end
  end
  resources :sales_reports
  resources :prospects
  resources :products
  resources :customers do
    collection do
      get :import_form
      post :import
    end
  end
  resources :company_informations, only: [:edit, :update]
  resources :user_profiles
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :user_registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations'
  end

  root to: 'static_pages#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  belongs_to :company_information
  has_many :sales_report, dependent: :restrict_with_error
  has_many :estimate, dependent: :restrict_with_error
  has_many :prospect, dependent: :restrict_with_error

  validates :name, presence: true, length: { maximum: 50 }

  scope :actives, -> {
    joins(:user).where("users.disabled_at IS NULL")
  }

  scope :search, -> (word) {
    joins(:user).where("name LIKE :word OR users.email LIKE :word", word: "\%#{word}\%")
  }
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @query = params[:query]
    @user_profiles = current_user_company.user_profiles.actives.search(@query).order(:name).paginate(page: params[:page], per_page: 20)
  end

  def new
    @user = User.new
    @user_profile = @user.build_user_profile
    @user_profile.company_information = current_user_company
  end

  def create
    @user = User.new(user_params)
    @user.user_profile.company_information = current_user_company
    if @user.save
      flash[:notice] = t('.user_created')
      redirect_to user_profiles_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      sign_in(@user, bypass: true)
      flash[:notice] = t('.user_updated')
      redirect_to user_profiles_url
    else
      render 'edit'
    end
  end

  def destroy
    if @user.disable
      flash[:notice] = t('.user_was_disabled')
    else
      flash[:danger] = t('.user_disable_was_failed')
    end
    redirect_to user_profiles_url
  end

  private

    def user_params
      if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      params.require(:user).permit(:id, :email, :password, :password_confirmation, user_profile_attributes: [:id, :name])
    end

    def set_user
      user_id = params[:id]
      @user = current_user_company.user_profiles.find_by!(user_id: user_id).user
    end

end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/user_profiles/_form.html.erb
<%= form_with(model: user, local: true, class: 'form-horizontal', url: path, method: method) do |form| %>
  <%= render 'shared/error_messages', object: user %>

  <%= form.fields_for :user_profile do |f| %>
    <div class="form-group">
      <%= f.hidden_field :id %>
      <div class="field">
        <%= f.label :name, class: 'control-label col-sm-2' %>
        <div class="col-sm-5">
          <%= f.text_field :name, autofocus: true, id: :product_name, class: 'form-control form-control-sm' %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :email, class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= form.email_field :email, class: 'form-control form-control-sm' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :password, class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= form.password_field :password, class: 'form-control form-control-sm' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :password_confirmation, class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= form.password_field :password_confirmation, class: 'form-control form-control-sm' %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-1"></div>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary col-sm-1' %>
    </div>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<p class="text-danger"><%= t('.if_you_wont_change_password_please_empty_password_field') %></p>

<%= render 'form', user: @user, path: user_profile_path(@user), method: :patch %>

app/views/user_profiles/index.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<div class="row">
  <%= form_tag user_profiles_path, method: :get, class: 'col-sm-6' do %>
    <div class="input-group input-group-sm">
      <%= text_field_tag :query, @query, class: 'form-control input-sm', placeholder: t('.search_word_placeholder') %>
      <span class="input-group-btn">
        <%= button_tag class: 'btn btn-default btn-sm' do %>
          <%= content_tag :span, t('.search') %>
        <% end %>
      </span>
    </div>
  <% end %>

  <div class="pull-right col-sm-4">
    <%= link_to t('.new_entry'), new_user_profile_path, class: 'btn btn-primary btn-sm' %>
  </div>
</div>

<div class="row mt-3"></div>

<table class="table table-hover table-sm">
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.user_profile.name') %></th>
      <th><%= t('activerecord.attributes.user.email') %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.user.email %></td>
        <td><%= link_to t('.edit'), edit_user_profile_path(profile), class: 'btn btn-info btn-sm' %></td>
        <td>
          <% unless profile.user.last_user? %>
            <%= link_to t('.disable'), user_profile_path(profile), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: t('.are_you_sure') } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @user_profiles, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/user_profiles/new.html.erb
<div class="row mt-3"></div>

<h4><%= t('.title') %></h4>

<%= render 'form', user: @user, path: user_profiles_path, method: :post %>