config/routes.rb
Rails.application.routes.draw do
  resources :closing_groups
  resources :earnings
  resources :delivery_slips
  resources :orders
  resources :order_details, only: [:show]
  resources :estimates do
    member do
      get :report
    end
  end
  resources :sales_reports
  resources :prospects
  resources :products
  resources :customers do
    collection do
      get :import_form
      post :import
    end
  end
  resources :company_informations, only: [:edit, :update]
  resources :user_profiles
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :user_registration,
      only: [:new, :create],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'registrations'
  end

  root to: 'static_pages#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails CRM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if signed_in? %>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <!-- brand -->
      <%= link_to 'Rails CRM', root_path, class: 'navbar-brand' %>
      <!-- toggle button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- menu -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= active_class(SalesReportsController.controller_name) %>"><%= link_to t('layout.sales_reports'), sales_reports_path, class: 'nav-link' %></li>
          <li class="nav-item <%= active_class(ProspectsController.controller_name) %>"><%= link_to t('layout.prospects'), prospects_path, class: 'nav-link' %></li>
          <li class="nav-item <%= active_class(EstimatesController.controller_name) %>"><%= link_to t('layout.estimates'), estimates_path, class: 'nav-link' %></li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item dropdown <%= active_class %>">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">設定<span class="caret"></span></a>
            <div class="dropdown-menu navbar-dark" role="menu">
              <%= link_to t('layout.customers'), customers_path, class: 'dropdown-item' %>
              <%= link_to t('layout.products'), products_path, class: 'dropdown-item' %>
              <%= link_to t('layout.mysetting'), edit_company_information_path(current_user_company), class: 'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item"><span class="nav-link disabled"><%= welcome_message %></span></li>
          <li class="nav-item"><%= link_to t('devise.signout'), destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        </ul>
      </div>
    </nav>
    <% end %>
    <div class="container-fluid">
      <% flash.each do |key, value| %>
        <% key = "info" if key == "notice" %>
        <% key = "danger" if key == "alert" %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>